# Using single stage build for fast local dev

FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

# Caching dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# Copying project source
COPY . /app

# Installing dependencies including the app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

# Creating non-root user
RUN groupadd --system --gid 999 appuser \
 && useradd --system --gid 999 --uid 999 --create-home appuser

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1

USER appuser

CMD ["flask", "run"]
